AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'node_modules/**/*'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Lint/ScriptPermission:
  Enabled: false

Layout/LineLength:
  Max: 120
